name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install terraform-docs
      uses: jaxxstorm/action-install-gh-release@v1
      with:
        repo: terraform-docs/terraform-docs
        tag: v0.16.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: pre-commit/action@v2.0.3
